version: '3'

services:
  db:
    build: ./postgrdb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  ginapi:
    build: ./apigin
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow

  mainapp:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db
      - ginapi
    networks:
      - mynetwork
    environment:
      TZ: Europe/Moscow

networks:
  mynetwork: {}