version: '3'

services:
  db:
    build: ./postgrdb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  apigin:
    build: ./apigin
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8085:8085"
    networks:
      - mynetwork
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow

  mainapp:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db
      - apigin
    networks:
      - mynetwork
    environment:
      TZ: Europe/Moscow

networks:
  mynetwork: {}